In [2]:
from sklearn.datasets import fetch_openml
import numpy as np
import pickle
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.metrics import confusion_matrix
from sklearn.cluster import DBSCAN

In [3]:
mnist= fetch_openml('mnist_784', version=1, as_frame=False, parser='auto')
mnist.target=mnist.target.astype(np.uint8)
X=mnist["data"]
y=mnist["target"]

In [4]:
silhouette_array = []
labels10 = list()
k_array = [8, 9, 10, 11, 12]
for k in k_array:
    kmeans = KMeans(n_clusters=k, random_state=42)
    y_predict = kmeans.fit_predict(X)
    k_silhouette = silhouette_score(X, kmeans.labels_)
    print(f'{k}-centroids: {k_silhouette}')
    silhouette_array.append(k_silhouette)
    if k == 10:
        labels10 = kmeans.labels_
print(silhouette_array)

8-centroids: 0.0734131342189013
9-centroids: 0.07455228544765777
10-centroids: 0.058589960042872244
11-centroids: 0.05835320507284715
12-centroids: 0.0600085166703175
[0.0734131342189013, 0.07455228544765777, 0.058589960042872244, 0.05835320507284715, 0.0600085166703175]


In [5]:
with open('kmeans_sil.pkl', 'wb') as filename:
    pickle.dump(silhouette_array, filename)

In [6]:
conf_mat = confusion_matrix(y, labels10)
print(conf_mat)

[[  20   35  208   26 3192 2987   22    3  205  205]
 [   9    6   10 3463    0    0    9 4362    9    9]
 [4888  201  175  458   14  113   81  413  236  411]
 [ 270  196 1177  112   15  128   56  495   61 4631]
 [  40 3730   27  348   14   11 2256  186  212    0]
 [  21  432 1879  897   73  251  420  185  131 2024]
 [  92   90  128  262  123  137    2  324 5685   33]
 [  52 2082   10  342   16   15 4391  375    5    5]
 [  67  228 4038  477   44   40  219  325   57 1330]
 [  14 3440   82  128   46   29 2853  262   13   91]]


In [8]:
argmax_array = []
for row in conf_mat:
    argmax_array.append(np.argmax(row))
print(argmax_array)
argmax_array.sort()
argmax_array = set(argmax_array)
argmax_array = list(argmax_array)
print(argmax_array)

[4, 7, 0, 9, 1, 9, 8, 6, 2, 1]
[0, 1, 2, 4, 6, 7, 8, 9]


In [9]:
with open('kmeans_argmax.pkl', 'wb') as filename:
    pickle.dump(argmax_array, filename)

In [10]:
distances = []
for i in range(300):
    for j in range(X.shape[0]):
        if i != j:
            distance = np.linalg.norm(X[i] - X[j])
            if distance == 0:
                continue
            else:
                distances.append(distance)
distances.sort()
distances = distances[:10]
print(distances)

[1020.6473436011089, 1100.529418052966, 1114.2374073777994, 1125.4843401842604, 1125.6913431309667, 1134.3138895385175, 1143.500765194322, 1149.3206689170781, 1166.3618649458667, 1167.1088209760048]


In [11]:
with open('dist.pkl', 'wb') as filename:
    pickle.dump(distances, filename)

In [ ]:
mean_distance = (distances[0] + distances[1] + distances[2]) / 3.0
end = 1.1 * mean_distance
step = 0.04 * mean_distance
tmp_value = mean_distance
dbscan_array = []
while tmp_value <= end:
    dbscan = DBSCAN(eps=tmp_value)
    dbscan.fit(X)
    print(dbscan.labels_[:15])
    labels = dbscan.labels_
    unique_labels = len(np.unique(labels))
    dbscan_array.append(unique_labels)
    tmp_value += step

In [1]:
print(dbscan_array)
with open('dbscan_len.pkl', 'wb') as filename:
    pickle.dump(dbscan_array, filename)

NameError: name 'dbscan_array' is not defined